"""Making user_node_id on user_sets mandatory

Revision ID: 05b6dbbbbb67
Revises: a57be74fc268
Create Date: 2025-04-12 22:10:44.124219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05b6dbbbbb67'
down_revision: Union[str, None] = 'a57be74fc268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
