"""Added new card fields for algorithm

Revision ID: 0c21e99ca247
Revises: eba6cbb5f6f0
Create Date: 2025-06-08 15:35:27.455908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c21e99ca247'
down_revision: Union[str, None] = 'eba6cbb5f6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'user_card',
        sa.Column('ease_factor', sa.Float(), nullable=False, server_default=sa.text('2.5'))
    )
    op.add_column(
        'user_card',
        sa.Column('learning_step_index', sa.SmallInteger(), nullable=False, server_default=sa.text('0'))
    )
    op.add_column(
        'user_card',
        sa.Column('is_graduated', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.add_column(
        'user_card',
        sa.Column('current_interval_days', sa.Integer(), nullable=False, server_default=sa.text('0'))
    )
    op.add_column(
        'user_card',
        sa.Column('health', sa.Float(), nullable=False, server_default=sa.text('1.0'))
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_card', 'health')
    op.drop_column('user_card', 'current_interval_days')
    op.drop_column('user_card', 'is_graduated')
    op.drop_column('user_card', 'learning_step_index')
    op.drop_column('user_card', 'ease_factor')
    # ### end Alembic commands ###
