"""Add relationship to user_node for version targeting. Make versioning

Revision ID: 491828f5e333
Revises: 8944c8bf9b18
Create Date: 2025-03-22 18:37:53.633813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '491828f5e333'
down_revision: Union[str, None] = '8944c8bf9b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('set', 'node_version_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('user_card', sa.Column('user_node_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_user_card_user_node_id', 'user_card', 'user_node', ['user_node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_card_user_node_id', 'user_card', type_='foreignkey')
    op.drop_column('user_card', 'user_node_id')
    op.alter_column('set', 'node_version_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
