"""Adding created_by column for sets for RLS

Revision ID: 5c6c1a19ec2a
Revises: d5c4afbb2636
Create Date: 2025-03-23 19:31:40.950317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c6c1a19ec2a'
down_revision: Union[str, None] = 'd5c4afbb2636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('created_by', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'created_by')
    # ### end Alembic commands ###
