"""Adding updated_at timestamps, changing url from set to node

Revision ID: 639312f25c9b
Revises: 491828f5e333
Create Date: 2025-03-23 19:24:45.110482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '639312f25c9b'
down_revision: Union[str, None] = '491828f5e333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'updated_at')
    # ### end Alembic commands ###
