"""Added in update field, added some FK's for user_node

Revision ID: 746cc0368842
Revises: f9c8190a652d
Create Date: 2025-04-26 15:36:33.609011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '746cc0368842'
down_revision: Union[str, None] = 'f9c8190a652d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('card_identity_id', sa.Uuid(), nullable=False))
    op.add_column('card', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('card', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.drop_constraint('fk_card_card_identity', 'card', type_='foreignkey')
    op.create_foreign_key('fk_card_card_identity_id', 'card', 'card_identity', ['card_identity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_node_created_by', 'card', 'deku_user', ['created_by'], ['id'])
    op.drop_column('card', 'card_identity')
    op.create_foreign_key('fk_node_created_by', 'set', 'deku_user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_node_created_by', 'set', type_='foreignkey')
    op.add_column('card', sa.Column('card_identity', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_node_created_by', 'card', type_='foreignkey')
    op.drop_constraint('fk_card_card_identity_id', 'card', type_='foreignkey')
    op.create_foreign_key('fk_card_card_identity', 'card', 'card_identity', ['card_identity'], ['id'], ondelete='CASCADE')
    op.drop_column('card', 'created_by')
    op.drop_column('card', 'updated_at')
    op.drop_column('card', 'card_identity_id')
    # ### end Alembic commands ###
