"""Adding FK's

Revision ID: 94c2b044c071
Revises: a293223bf671
Create Date: 2025-03-22 16:45:23.248212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94c2b044c071'
down_revision: Union[str, None] = 'a293223bf671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PublicNode', sa.Column('current_version', sa.Uuid(), nullable=False))
    op.drop_column('PublicNode', 'targeted_version')
    op.add_column('UserNodes', sa.Column('node_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserNodes', 'node_enabled')
    op.add_column('PublicNode', sa.Column('targeted_version', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_column('PublicNode', 'current_version')
    # ### end Alembic commands ###
