"""Changing PK from composite to single id, made changes directly to db

Revision ID: 9cfbf8b220a9
Revises: df414cac8e06
Create Date: 2025-03-24 21:23:33.582096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9cfbf8b220a9'
down_revision: Union[str, None] = 'df414cac8e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
