"""Adding links for userCards and userSets to userNodes in order to fetch version

Revision ID: a293223bf671
Revises: 60bdb3bbafc0
Create Date: 2025-03-08 16:42:20.819708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a293223bf671'
down_revision: Union[str, None] = '60bdb3bbafc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Nodes', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('Sets', sa.Column('set_identity_id', sa.Uuid(), nullable=False))
    op.add_column('Sets', sa.Column('parent_set_id', sa.Uuid(), nullable=False))
    op.add_column('Sets', sa.Column('x_relative_node', sa.Float(), nullable=False))
    op.add_column('Sets', sa.Column('y_relative_node', sa.Float(), nullable=False))
    op.add_column('UserCards', sa.Column('user_set_id', sa.Uuid(), nullable=False))
    op.add_column('UserSets', sa.Column('user_node_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserSets', 'user_node_id')
    op.drop_column('UserCards', 'user_set_id')
    op.drop_column('Sets', 'y_relative_node')
    op.drop_column('Sets', 'x_relative_node')
    op.drop_column('Sets', 'parent_set_id')
    op.drop_column('Sets', 'set_identity_id')
    op.drop_column('Nodes', 'title')
    # ### end Alembic commands ###
