"""Making title for nodes nullable

Revision ID: a57be74fc268
Revises: e4bc8221342e
Create Date: 2025-03-30 18:00:13.060591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a57be74fc268'
down_revision: Union[str, None] = 'e4bc8221342e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('group_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('node', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('node', 'group_title')
    # ### end Alembic commands ###
