"""Changing parent_set_id to be nullable

Revision ID: b4e77d133ff5
Revises: 639312f25c9b
Create Date: 2025-03-23 19:27:00.953480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4e77d133ff5'
down_revision: Union[str, None] = '639312f25c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('set', 'parent_set_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('set', 'parent_set_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
