"""Removing created_by column for sets

Revision ID: d5c4afbb2636
Revises: b4e77d133ff5
Create Date: 2025-03-23 19:30:21.022715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5c4afbb2636'
down_revision: Union[str, None] = 'b4e77d133ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
