"""Changing fk to right table

Revision ID: df414cac8e06
Revises: 5c6c1a19ec2a
Create Date: 2025-03-24 19:59:45.599397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df414cac8e06'
down_revision: Union[str, None] = '5c6c1a19ec2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_set_set_identity_id', 'user_set', type_='foreignkey')
    op.create_foreign_key('fk_user_set_set_identity_id', 'user_set', 'set_identity', ['set_identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_set_set_identity_id', 'user_set', type_='foreignkey')
    op.create_foreign_key('fk_user_set_set_identity_id', 'user_set', 'set', ['set_identity_id'], ['id'])
    # ### end Alembic commands ###
