"""Changes to FK's, Changes to column names to keep consistancy

Revision ID: e4bc8221342e
Revises: 9cfbf8b220a9
Create Date: 2025-03-25 19:57:52.051163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4bc8221342e'
down_revision: Union[str, None] = '9cfbf8b220a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('public_node', sa.Boolean()))
    op.execute("UPDATE node SET public_node = false WHERE public_node IS NULL")
    op.alter_column('node', 'public_node', nullable=False)
    op.drop_column('node', 'public_set')
    op.add_column('public_node', sa.Column('creator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('set', sa.Column('title', sqlmodel.sql.sqltypes.AutoString()))
    op.execute('UPDATE "set" SET title = \'\' WHERE title IS NULL')
    op.alter_column('set', 'title', nullable=False)
    op.add_column('set', sa.Column('relative_x', sa.Float(), nullable=False, server_default=sa.text('0')))
    op.add_column('set', sa.Column('relative_y', sa.Float(), nullable=False, server_default=sa.text('0')))
    op.drop_column('set', 'x_relative_node')
    op.drop_column('set', 'name')
    op.drop_column('set', 'y_relative_node')
    op.add_column('user_node', sa.Column('position_x', sa.Float(), nullable=False, server_default=sa.text('0')))
    op.add_column('user_node', sa.Column('position_y', sa.Float(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_node', 'position_y')
    op.drop_column('user_node', 'position_x')
    op.add_column('set', sa.Column('y_relative_node', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('set', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('set', sa.Column('x_relative_node', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('set', 'relative_y')
    op.drop_column('set', 'relative_x')
    op.drop_column('set', 'title')
    op.drop_column('public_node', 'creator_name')
    op.add_column('node', sa.Column('public_set', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('node', 'public_node')
    # ### end Alembic commands ###
