"""desc renamed to description

Revision ID: f9c8190a652d
Revises: 9fc099aaa1b4
Create Date: 2025-04-25 20:02:47.678189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9c8190a652d'
down_revision: Union[str, None] = '9fc099aaa1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('parent_set_id', sa.Uuid(), nullable=False))
    op.create_foreign_key('fk_card_set_id', 'card', 'set', ['parent_set_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_card_set_id', 'card', type_='foreignkey')
    op.drop_column('card', 'parent_set_id')
    # ### end Alembic commands ###
